# Docker Compose configuration for HealthTracker Frontend
version: '3.8'

services:
  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: healthtracker-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8080
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - healthtracker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend application (reference)
  backend:
    image: healthtracker-backend:latest
    container_name: healthtracker-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/healthtracker
      - SPRING_DATASOURCE_USERNAME=healthtracker
      - SPRING_DATASOURCE_PASSWORD=healthtracker123
    depends_on:
      - database
    networks:
      - healthtracker-network
    restart: unless-stopped

  # Database
  database:
    image: mysql:8.0
    container_name: healthtracker-database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=healthtracker
      - MYSQL_USER=healthtracker
      - MYSQL_PASSWORD=healthtracker123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - healthtracker-network
    restart: unless-stopped

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: healthtracker-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - healthtracker-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  healthtracker-network:
    driver: bridge